# Generated by Django 4.2.3 on 2023-07-16 13:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.UUID('621ae721-e750-4e2a-95db-4de77e741a69'),
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.UUID('621ae721-e750-4e2a-95db-4de77e741a69'),
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.UUID('621ae721-e750-4e2a-95db-4de77e741a69'),
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(verbose_name=255)),
                ('timestamp', models.DateTimeField()),
                (
                    'room',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='chat.room'
                    )
                ),
                (
                    'sender',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='chat.user'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
