# Generated by Django 4.2.3 on 2023-07-16 13:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='roomId',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='senderId',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('d9a17a66-6168-40d6-a95e-973862c4c65c'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('d9a17a66-6168-40d6-a95e-973862c4c65c'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('d9a17a66-6168-40d6-a95e-973862c4c65c'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
    ]
