# Generated by Django 4.2.3 on 2023-07-16 18:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_room_message_roomid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('a3340431-5bd8-4ca8-a5bf-8d6cff5a9111'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderId',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='chat.user'
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('a3340431-5bd8-4ca8-a5bf-8d6cff5a9111'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('a3340431-5bd8-4ca8-a5bf-8d6cff5a9111'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
    ]
