# Generated by Django 4.2.3 on 2023-07-28 06:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    A Django migration class that represents a migration 
        operation to be performed on the database schema.
    """

    dependencies = [
        ('chat', '0003_alter_message_id_alter_message_senderid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='_id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('62414668-b1cf-4373-8bf0-05a7828a5875'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='_id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('62414668-b1cf-4373-8bf0-05a7828a5875'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID('62414668-b1cf-4373-8bf0-05a7828a5875'),
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderId',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='chat.user'
            ),
        ),
    ]
